# Generated by Django 4.1.7 on 2025-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
