# Generated by Django 4.1.7 on 2025-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_alter_option_options_option_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('form', 'order')},
        ),
    ]
